Repository uti1man/dimencart, pull requests merged in 2022-10, with the labels that each got.

#2 fixing nav bar links responsiveness issue
  index.html
  src/css/navbar.css
Labels: hacktoberfest, ui

#17 Create README.md
  README.md
Labels: hacktoberfest

#26 Added contributors and license in README.md
  README.md
Labels: documentation, hacktoberfest, ui, hacktoberfest-accepted

#37 Update index.html
  index.html
Labels: good first issue, hacktoberfest
